---
- name: Deploy NetBox application
  hosts: "{{ lookup('env', 'ANSIBLE_LIMIT') | default('netbox', true) }}"
  become: true
  gather_facts: false

  vars_files:
    - ../config.yaml

  vars:
    netbox_external_url: "{{ netbox.external_url }}"
    netbox_allowed_hosts: "{{ netbox.allowed_hosts }}"
    netbox_listen_address: "{{ netbox.listen_address }}"
    netbox_http_port: "{{ netbox.http_port }}"
    netbox_docker_version: "{{ netbox.docker_version }}"
    netbox_api_token_pepper: "{{ lookup('env', 'NETBOX_API_TOKEN_PEPPER') }}"
    netbox_postgresql_host: "{{ netbox.postgresql.host }}"
    netbox_postgresql_port: "{{ netbox.postgresql.port }}"
    netbox_postgresql_database: "{{ netbox.postgresql.database }}"
    netbox_postgresql_username: "{{ netbox.postgresql.username }}"
    netbox_redis_host: "{{ netbox.redis.host }}"
    netbox_redis_port: "{{ netbox.redis.port }}"
    netbox_redis_database: "{{ netbox.redis.database | default(0) }}"
    netbox_redis_cache_database: "{{ netbox.redis.cache_database | default(1) }}"
    netbox_redis_password: "{{ lookup('env', 'REDIS_PASSWORD') }}"
    netbox_superuser_name: "{{ lookup('env', 'NETBOX_SUPERUSER_NAME') }}"
    netbox_oidc_scope: "{{ netbox.oidc.scope }}"
    netbox_oidc_provider: "{{ netbox.oidc.provider | default('authentik') }}"
    authentik_issuer_url: "{{ netbox.oidc.issuer_url }}"
    authentik_client_id: "{{ netbox.oidc.client_id }}"
    authentik_logout_redirect_url: "{{ netbox.oidc.logout_redirect_url }}"
    authentik_client_secret: "{{ lookup('env', 'AUTHENTIK_CLIENT_SECRET') }}"
    keycloak_issuer_url: "{{ netbox.oidc.keycloak.issuer_url }}"
    keycloak_netbox_client_id: "{{ netbox.oidc.keycloak.client_id }}"
    keycloak_logout_redirect_url: "{{ netbox.oidc.keycloak.logout_redirect_url }}"
    keycloak_netbox_client_secret: "{{ lookup('env', 'KEYCLOAK_NETBOX_CLIENT_SECRET') }}"
    netbox_oidc_issuer_url: "{{ keycloak_issuer_url if netbox_oidc_provider == 'keycloak' else authentik_issuer_url }}"
    netbox_oidc_client_id: "{{ keycloak_netbox_client_id if netbox_oidc_provider == 'keycloak' else authentik_client_id }}"
    netbox_oidc_client_secret: "{{ keycloak_netbox_client_secret if netbox_oidc_provider == 'keycloak' else authentik_client_secret }}"
    netbox_oidc_logout_redirect_url: "{{ keycloak_logout_redirect_url if netbox_oidc_provider == 'keycloak' else authentik_logout_redirect_url }}"
    netbox_secret_key: "{{ lookup('env', 'NETBOX_SECRET_KEY') }}"
    netbox_postgres_password: "{{ lookup('env', 'NETBOX_POSTGRES_PASSWORD') }}"
    netbox_superuser_email: "{{ lookup('env', 'NETBOX_SUPERUSER_EMAIL') }}"
    netbox_superuser_password: "{{ lookup('env', 'NETBOX_SUPERUSER_PASSWORD') }}"
    netbox_superuser_api_token: "{{ lookup('env', 'NETBOX_SUPERUSER_API_TOKEN') }}"

  pre_tasks:
    - ansible.builtin.import_tasks: ../../../shared/ansible/tasks/bootstrap_python.yml

  roles:
    - netbox_app
    - monitoring_agent
    - logging_agent
