---
- name: Read public CA certificate from service host
  ansible.builtin.slurp:
    src: "{{ traefik_proxy_root_ca_source.source }}"
  register: traefik_proxy_root_ca_content
  no_log: true

- name: Install public CA certificate on Traefik hosts
  ansible.builtin.copy:
    content: "{{ traefik_proxy_root_ca_content.content | b64decode }}"
    dest: "{{ traefik_proxy_root_ca_source.destination }}"
    owner: root
    group: root
    mode: "0644"
  delegate_to: "{{ traefik_target_host }}"
  loop: "{{ traefik_proxy_hosts }}"
  loop_control:
    loop_var: traefik_target_host
