---
- name: Pull compose images
  community.docker.docker_compose_v2:
    project_src: "{{ compose_app_root }}"
    files:
      - "{{ compose_app_compose_file | basename }}"
    state: present
    pull: always
    recreate: never
