---
- name: Restart NetBox
  ansible.builtin.include_tasks: "{{ role_path }}/../compose_app/tasks/reconcile.yml"
  vars:
    compose_app_handler_project_src: "{{ netbox_compose_dir }}"
    compose_app_handler_remove_orphans: true
