---
traefik_image_tag: "{{ lookup('env', 'TRAEFIK_IMAGE_TAG') | default('v3.7.1', true) }}"
traefik_listen_address: "{{ lookup('env', 'TRAEFIK_LISTEN_ADDRESS') | default('0.0.0.0', true) }}"
traefik_http_port: "{{ lookup('env', 'TRAEFIK_HTTP_PORT') | default('80', true) | int }}"
traefik_https_port: "{{ lookup('env', 'TRAEFIK_HTTPS_PORT') | default('443', true) | int }}"
traefik_acme_email: "{{ lookup('env', 'TRAEFIK_ACME_EMAIL') }}"
traefik_domain: "{{ lookup('env', 'TRAEFIK_DOMAIN') | default('example.test', true) }}"
traefik_dns_provider: "{{ lookup('env', 'TRAEFIK_DNS_PROVIDER') | default('selectelv2', true) }}"
traefik_dashboard_host: "{{ lookup('env', 'TRAEFIK_DASHBOARD_HOST') | default('traefik.example.test', true) }}"
traefik_keycloak_dashboard_host: "{{ lookup('env', 'TRAEFIK_KEYCLOAK_DASHBOARD_HOST') | default('traefik-keycloak.example.test', true) }}"

selectelv2_account_id: "{{ lookup('env', 'SELECTELV2_ACCOUNT_ID') }}"
selectelv2_project_id: "{{ lookup('env', 'SELECTELV2_PROJECT_ID') }}"
selectelv2_username: "{{ lookup('env', 'SELECTELV2_USERNAME') }}"
selectelv2_password: "{{ lookup('env', 'SELECTELV2_PASSWORD') }}"

authentik_url: "{{ lookup('env', 'AUTHENTIK_URL') | default('http://192.0.2.11:9000', true) }}"
proxmox_web_url: "{{ lookup('env', 'PROXMOX_WEB_URL') | default('https://192.0.2.2:8006', true) }}"
pbs_web_url: "{{ lookup('env', 'PBS_WEB_URL') | default('https://192.0.2.2:8007', true) }}"
truenas_web_url: "{{ lookup('env', 'TRUENAS_WEB_URL') | default('https://192.0.2.130:443', true) }}"
gitlab_url: "{{ lookup('env', 'GITLAB_URL') | default('http://192.0.2.10:80', true) }}"
gitlab_ssh_address: "{{ lookup('env', 'GITLAB_SSH_ADDRESS') | default('192.0.2.10:2222', true) }}"
netbox_url: "{{ lookup('env', 'NETBOX_SERVICE_URL') | default('http://192.0.2.11:80', true) }}"
dockerhub_url: "{{ lookup('env', 'DOCKERHUB_URL') | default('http://192.0.2.12:5000', true) }}"
