---
- name: Deploy Grafana
  hosts: "{{ lookup('env', 'ANSIBLE_LIMIT') | default('grafana', true) }}"
  become: true
  gather_facts: false

  vars_files:
    - ../config.yaml

  vars:
    grafana_dashboards_source_dir: "{{ playbook_dir }}/../dashboards"
    grafana_alerting_source_file: "{{ playbook_dir }}/../alerts/alerting.yml.j2"
    download_url: "{{ grafana.download_url }}"
    grafana_oidc_client_secret: "{{ lookup('env', 'GRAFANA_OIDC_CLIENT_SECRET') }}"
    grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"
    grafana_s3_access_key: "{{ lookup('env', 'GRAFANA_S3_ACCESS_KEY') }}"
    grafana_s3_secret_key: "{{ lookup('env', 'GRAFANA_S3_SECRET_KEY') }}"
    grafana_telegram_bot_token: "{{ lookup('env', 'GRAFANA_TELEGRAM_BOT_TOKEN') }}"
    grafana_telegram_chat_id: "{{ lookup('env', 'GRAFANA_TELEGRAM_CHAT_ID') }}"
    grafana_proxmox_api_token: "{{ lookup('env', 'GRAFANA_PROXMOX_API_TOKEN') }}"
    grafana_postgresql_password: "{{ lookup('env', 'POSTGRESQL_PROMETHEUS_PASSWORD') }}"
    grafana_forgejo_metrics_token: "{{ lookup('env', 'FORGEJO_INTERNAL_TOKEN') }}"
    grafana_redis_exporter_password: "{{ lookup('env', 'REDIS_PASSWORD') }}"

  pre_tasks:
    - ansible.builtin.import_tasks: ../../../shared/ansible/tasks/bootstrap_python.yml

  roles:
    - grafana_app
    - monitoring_agent
    - logging_agent
