---
stages:
  - generate
  - include

generate-pipeline:
  stage: generate
  script:
    - python3 -c "import jinja2, yaml"
    - python3 shared/scripts/generate_terraform_state_migration.py > generated-terraform-state-migration.yml
  artifacts:
    paths:
      - generated-terraform-state-migration.yml
    expire_in: 1 day

terraform-state-migration-pipeline:
  stage: include
  allow_failure: true
  trigger:
    include:
      - artifact: generated-terraform-state-migration.yml
        job: generate-pipeline
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true
