---
galaxy_info:
  role_name: freeipa_app
  author: drg
  description: Deploy native replicated FreeIPA/IdM servers
  license: MIT
  min_ansible_version: "2.14"

dependencies:
  - role: debian_mirrors
