{
 "title": "Proxmox",
 "tags": [
  "proxmox",
  "pve"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Guest status",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "pve_up * on(id) group_left(name) pve_guest_info"
    }
   ]
  },
  {
   "title": "Guests without backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pve_not_backed_up_total)" }
   ]
  },
  {
   "title": "Guest CPU %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (pve_cpu_usage_ratio * on(id) group_left(name) pve_guest_info)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Guest RAM %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ((pve_memory_usage_bytes / pve_memory_size_bytes) * on(id) group_left(name) pve_guest_info)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node CPU %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * pve_cpu_usage_ratio{id=~\"node/(nas|server)\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Node RAM %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (pve_memory_usage_bytes{id=~\"node/(nas|server)\"} / pve_memory_size_bytes{id=~\"node/(nas|server)\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Guest disk I/O throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes_total[5m]) * on(id) group_left(name) pve_guest_info",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "rate(pve_disk_written_bytes_total[5m]) * on(id) group_left(name) pve_guest_info",
     "legendFormat": "{{name}} write"
    }
   ]
  }
 ]
}