---
redis_port: 6379
redis_sentinel_port: 26379
redis_listen_address: "0.0.0.0"
redis_data_dir: /var/lib/redis
redis_sentinel_data_dir: /var/lib/redis-sentinel
redis_master_name: drg-redis
redis_quorum: 2
redis_down_after_milliseconds: 5000
redis_failover_timeout: 60000
redis_parallel_syncs: 1
redis_dns_zone: example.test
redis_password: ""
